fixes
Signed-off-by: aerosouund <aerosound161@gmail.com>

diff --git a/test/conformance/chainsaw/reports-exclude-result/chainsaw-test.yaml b/test/conformance/chainsaw/reports-exclude-result/chainsaw-test.yaml
--- a/test/conformance/chainsaw/reports-exclude-result/chainsaw-test.yaml
+++ b/test/conformance/chainsaw/reports-exclude-result/chainsaw-test.yaml
@@ -5,16 +5,22 @@ metadata:
   name: update-deployment
 spec:
   steps:
+  - name: create ns
+    try:
+    - apply:
+        file: namespace.yaml
+    - assert:
+        file: namespace.yaml
   - name: create policy
     use:
-      template: ../../../_step-templates/create-policy.yaml
+      template: ../_step-templates/create-policy.yaml
       with:
         bindings:
         - name: file
           value: policy.yaml
   - name: wait policy ready
     use:
-      template: ../../../_step-templates/cluster-policy-ready.yaml
+      template: ../_step-templates/cluster-policy-ready.yaml
       with:
         bindings:
         - name: name
@@ -22,28 +28,28 @@ spec:
   - name: step-02
     try:
     - apply:
-        file: deployment.yaml
+        file: deployment-bad.yaml
     - assert:
-        file: deployment.yaml
+        file: deployment-bad.yaml
   - name: step-03
     try:
-    - sleep:
-        duration: 5s
+    - apply:
+        file: deployment-good.yaml
+    - assert:
+        file: deployment-good.yaml
   - name: step-04
     try:
-    - assert:
-        file: report-assert.yaml
-  - name: step-05
-    try:
-    - apply:
-        file: update-deployment.yaml
-    - assert:
-        file: update-deployment.yaml
-  - name: step-06
-    try:
     - sleep:
         duration: 5s
-  - name: step-07
+  - name: step-05
     try:
-    - assert:
-        file: report-assert.yaml
+    - script:
+        content: |
+          POLR_COUNT=$(kubectl get policyreports --namespace=myns --no-headers 2>/dev/null | wc -l)
+          if [ "$POLR_COUNT" -gt 1 ]; then
+            echo "ERROR: Policy reports are higher than 1 when they shouldn't!"
+            exit 1
+          else
+            echo "SUCCESS: Policy reports not generated as expected"
+            exit 0
+          fi
